# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fce011b6ce5e2b20cd2f7d376836cb7d45140b0b8ca04636c511c13f4b39930e8473aad72ac9ce1cf2729abad53fab014243c3b7c3b6eb1ce5dc54946cdc1150

test:
  secret_key_base: 823e635c89824e7073a7e24b0fc5de7314d4a5c3e6bfabea78b42510161a10e6208f910c894e76f57065e1cbf5e190389e220f5078388325de571f0c069e69dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
